# Generated by Django 3.2.7 on 2021-09-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
